# This is a basic workflow to help you get started with Actions

name: Test release version

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: |
          git lfs checkout
          git lfs pull
          
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Runs a set of commands using the runners shell
      - name: Prepare
        run: |
          python -m pip install --upgrade pip
          python -m pip install exifdate2fs
          
      - name: Run tests
        run: |
          
          exifdate2fs -v .
          exifdate2fs -v --rename .
          
